// <auto-generated />
namespace BigSchool_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateTBnew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateTBnew));
        
        string IMigrationMetadata.Id
        {
            get { return "202107090844353_updateTBnew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
